services:
  app:
    profiles:
      - production
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    env_file:
      - .env
    environment:
      - ORIGIN=http://localhost:3000
    ports:
      - ${PORT:-3000}:3000
  # sparql:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.sparql
  #   ports:
  #     - 3030:3030
    # restart: always
