version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: always
    ports:
      - 3000:3000
    environment:
      - PORT=3000
  sparql:
    build:
      context: .
      dockerfile: Dockerfile.sparql
    restart: always
    ports:
      - 3030:3030
